//! Cross-implementation differential test against the SynBioDex/SBOL-Converter
//! Java reference. For each committed reference conversion under
//! `tests/fixtures/cross-impl-sbolconverter/expected/` this runs the full
//! matrix and compares normalized RDF triple sets:
//!
//! 1. Same-direction agreement (2->3): reference vs sbol-rs, same SBOL 2 input.
//! 2. Same-direction agreement (3->2): reference vs sbol-rs, same SBOL 3 input.
//! 3. Cross-tool round-trip: reference 2->3, then sbol-rs 3->2, vs original.
//! 4. Cross-tool round-trip: reference 3->2, then sbol-rs 2->3, vs original.
//!
//! The reference outputs are generated by
//! `regenerate-cross-impl-reference` (Docker, contributor-only); this test
//! needs no Docker/JVM.
//!
//! Comparison is on logical equivalence. [`logical`] content-addresses the
//! auto-generated `Constraint<N>` IRIs — the reference assigns their ordinal in
//! its Java `HashSet` iteration order, so the label a given constraint receives
//! carries no meaning — letting a label permutation compare equal while any
//! real structural difference still fails. [`logical_roundtrip`] additionally
//! strips conversion provenance and collapses version-equivalent references, so
//! a reference to an object's persistent identity matches a reference to its
//! single concrete version.
//!
//! GATED (must be logically equivalent):
//! - Same-direction agreement: reference and sbol-rs convert identical input
//!   the same way, in each direction.
//! - `ref-up->rs-down`: SBOL 2 -> reference SBOL 3 -> sbol-rs SBOL 2 == original.
//!
//! REPORTED, not gated:
//! - `ref-down->rs-up`: SBOL 3 -> reference SBOL 2 -> sbol-rs SBOL 3 vs original
//!   SBOL 3. SBOL 2 cannot represent a feature's orientation or a
//!   FunctionalComponent's locations, so the SBOL 3 -> SBOL 2 step discards them
//!   (both tools agree on that SBOL 2). Re-upgrading cannot restore what the
//!   SBOL 2 model does not hold; the residual is that model-expressiveness gap.

mod common;

use std::collections::BTreeSet;
use std::path::PathBuf;

use sbol3::{Document, RdfFormat};

/// stem -> SBOL 2 source fixture (relative to tests/fixtures/sbol2/).
const SBOL2_SOURCES: &[(&str, &str)] = &[
    (
        "component_definition_output",
        "SBOLTestSuite/SBOL2/ComponentDefinitionOutput.xml",
    ),
    (
        "module_definition_output",
        "SBOLTestSuite/SBOL2/ModuleDefinitionOutput.xml",
    ),
    (
        "sequence_constraint_output",
        "SBOLTestSuite/SBOL2/SequenceConstraintOutput.xml",
    ),
    (
        "repression_model",
        "SBOLTestSuite/SBOL2/RepressionModel.xml",
    ),
];

/// stem -> SBOL 3 source fixture (relative to tests/fixtures/sbol3/).
const SBOL3_SOURCES: &[(&str, &str)] = &[
    (
        "bba_f2620",
        "SBOLTestSuite/SBOL3/BBa_F2620_PoPSReceiver/BBa_F2620_PoPSReceiver.ttl",
    ),
    ("model", "SBOLTestSuite/SBOL3/entity/model/model.ttl"),
];

fn fixtures() -> PathBuf {
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.pop();
    p.pop();
    p.push("tests/fixtures");
    p
}

fn format_of(path: &str) -> RdfFormat {
    if path.ends_with(".ttl") {
        RdfFormat::Turtle
    } else {
        RdfFormat::RdfXml
    }
}

/// Canonical, sorted N-triples set of an RDF document (blank nodes
/// normalized), for order-insensitive graph comparison.
fn canon(text: &str, format: RdfFormat) -> BTreeSet<String> {
    let graph = sbol3::RdfGraph::parse(text, format).expect("parse rdf");
    graph
        .normalized_triples()
        .iter()
        .map(sbol_convert::canonical_nt_line)
        .collect()
}

fn canon_graph(graph: &sbol3::RdfGraph) -> BTreeSet<String> {
    graph
        .normalized_triples()
        .iter()
        .map(sbol_convert::canonical_nt_line)
        .collect()
}

/// The final path segment of an IRI when it is an auto-generated Constraint
/// name (`Constraint<N>`), else `None`. The converter mints these for each
/// MapsTo → Constraint decomposition and numbers them in `HashSet` iteration
/// order, so the ordinal identifies nothing; the comparison keys such a
/// Constraint by its content instead.
fn generated_constraint_segment(iri: &str) -> Option<&str> {
    let seg = iri.rsplit('/').next()?;
    let n = seg.strip_prefix("Constraint")?;
    (!n.is_empty() && n.bytes().all(|b| b.is_ascii_digit())).then_some(seg)
}

/// Canonicalizes a triple set for logical equivalence: each auto-generated
/// Constraint IRI is content-addressed by the multiset of its outgoing triples
/// (restriction / subject / object — everything but its ordinal `displayId`),
/// so those IRIs behave like blank nodes keyed by their surrounding structure.
/// A permutation of Constraint labels compares equal; any real structural
/// difference still shows up.
fn logical(lines: &BTreeSet<String>) -> BTreeSet<String> {
    // Subject IRI of a canonical N-Triples line, if it is an IRI.
    fn subject_iri(line: &str) -> Option<&str> {
        line.strip_prefix('<')
            .and_then(|rest| rest.split_once('>').map(|(iri, _)| iri))
    }
    let is_display_id = |line: &str| line.contains("> <http://sbols.org/v3#displayId> ");

    // Signature (sorted, minus displayId) of each generated Constraint.
    let mut sigs: std::collections::HashMap<&str, Vec<&str>> = std::collections::HashMap::new();
    for line in lines {
        if let Some(subj) = subject_iri(line)
            && generated_constraint_segment(subj).is_some()
            && !is_display_id(line)
        {
            // Store the "<predicate> object ." remainder, subject stripped.
            let remainder = &line[subj.len() + 2..];
            sigs.entry(subj).or_default().push(remainder);
        }
    }
    let rename: std::collections::HashMap<String, String> = sigs
        .into_iter()
        .map(|(iri, mut parts)| {
            parts.sort_unstable();
            (
                iri.to_owned(),
                format!("urn:constraint:{}", parts.join("\u{1f}")),
            )
        })
        .collect();

    lines
        .iter()
        .filter(|line| {
            // Drop the ordinal displayId of a generated Constraint.
            !(subject_iri(line).is_some_and(|s| rename.contains_key(s)) && is_display_id(line))
        })
        .map(|line| {
            let mut out = line.clone();
            for (iri, key) in &rename {
                out = out.replace(&format!("<{iri}>"), &format!("<{key}>"));
            }
            out
        })
        .collect()
}

/// Whether an IRI's final path segment is an SBOL 2 version (a leading-digit
/// `1`, `1.0`, `2.10.3`, …).
fn has_trailing_version(iri: &str) -> bool {
    iri.rsplit_once('/').is_some_and(|(_, last)| {
        last.starts_with(|c: char| c.is_ascii_digit())
            && last.bytes().all(|b| b.is_ascii_digit() || b == b'.')
    })
}

/// Round-trip normalization built on [`logical`]: also drops conversion
/// provenance (`backport/2_3#` annotations the upgrade stamps, never source
/// data) and collapses an SBOL 2 version segment (`.../X/1.0` ≡ `.../X`) so a
/// reference to an object's persistent identity matches a reference to its one
/// concrete version. What survives is genuine semantic divergence.
fn logical_roundtrip(lines: &BTreeSet<String>) -> BTreeSet<String> {
    let strip = |line: &str| -> String {
        line.split_inclusive('>')
            .map(|token| match token.rfind('<') {
                Some(open) => {
                    let iri = &token[open + 1..token.len() - 1];
                    let base = iri.rsplit_once('/').map(|(head, _)| head).unwrap_or(iri);
                    let kept = if has_trailing_version(iri) { base } else { iri };
                    format!("{}<{kept}>", &token[..open])
                }
                None => token.to_owned(),
            })
            .collect()
    };
    logical(lines)
        .iter()
        .filter(|line| !line.contains("sbols.org/backport/2_3#"))
        .map(|line| strip(line))
        .collect()
}

fn report(
    label: &str,
    reference: &BTreeSet<String>,
    sbol_rs: &BTreeSet<String>,
    norm: fn(&BTreeSet<String>) -> BTreeSet<String>,
) -> usize {
    let reference = &norm(reference);
    let sbol_rs = &norm(sbol_rs);
    let only_ref: Vec<&String> = reference.difference(sbol_rs).collect();
    let only_rs: Vec<&String> = sbol_rs.difference(reference).collect();
    let n = only_ref.len() + only_rs.len();
    if n == 0 {
        eprintln!("  [MATCH] {label}");
    } else {
        eprintln!("  [DIFF {n}] {label}");
        for t in only_ref.iter().take(6) {
            eprintln!("      only in reference: {t}");
        }
        for t in only_rs.iter().take(6) {
            eprintln!("      only in sbol-rs:   {t}");
        }
    }
    n
}

#[test]
fn cross_impl_reference_matrix() {
    let root = fixtures();
    let expected = root.join("cross-impl-sbolconverter/expected");
    let mut compared = 0usize;
    // (label, divergent-count) for every gated agreement check that was not
    // logically equivalent.
    let mut over_budget: Vec<(String, usize)> = Vec::new();

    eprintln!("\n=== SBOL2 -> SBOL3 (same-direction agreement + ref-up/rs-down round-trip) ===");
    for (stem, rel) in SBOL2_SOURCES {
        let ref_path = expected.join(format!("{stem}.sbolconverter.to-sbol3.nt"));
        let Ok(ref_text) = std::fs::read_to_string(&ref_path) else {
            continue;
        };
        let src = std::fs::read_to_string(root.join("sbol2").join(rel)).expect("read sbol2 src");
        let (rs_doc, _) = sbol_convert::upgrade_from_sbol2(&src, format_of(rel)).expect("upgrade");

        let ref_set = canon(&ref_text, RdfFormat::NTriples);
        let rs_set = canon_graph(rs_doc.rdf_graph());
        let n = report(
            &format!("2->3 agreement: {stem}"),
            &ref_set,
            &rs_set,
            logical,
        );
        if n > 0 {
            over_budget.push((format!("2->3 agreement: {stem}"), n));
        }
        compared += 1;

        // Cross-tool (reported, not gated): reference 2->3, sbol-rs 3->2, vs original.
        let ref3_doc = Document::read(&ref_text, RdfFormat::NTriples).expect("read ref3");
        let (rs2, _) = sbol_convert::downgrade(&ref3_doc).expect("downgrade ref3");
        let rs2_nt = rs2.write(RdfFormat::NTriples).expect("write nt");
        let orig_set = canon(&src, format_of(rel));
        let label = format!("ref-up->rs-down vs original: {stem}");
        let n = report(
            &label,
            &orig_set,
            &canon(&rs2_nt, RdfFormat::NTriples),
            logical_roundtrip,
        );
        if n > 0 {
            over_budget.push((label, n));
        }
    }

    eprintln!("\n=== SBOL3 -> SBOL2 (same-direction agreement + ref-down/rs-up round-trip) ===");
    for (stem, rel) in SBOL3_SOURCES {
        let ref_path = expected.join(format!("{stem}.sbolconverter.to-sbol2.rdf"));
        let Ok(ref_text) = std::fs::read_to_string(&ref_path) else {
            continue;
        };
        let src_path = root.join("sbol3").join(rel);
        let Ok(src) = std::fs::read_to_string(&src_path) else {
            continue;
        };
        let src_doc = Document::read(&src, RdfFormat::Turtle).expect("read sbol3 src");
        let (rs2, _) = sbol_convert::downgrade(&src_doc).expect("downgrade");
        let rs2_nt = rs2.write(RdfFormat::NTriples).expect("write nt");

        let ref_set = canon(&ref_text, RdfFormat::RdfXml);
        let n = report(
            &format!("3->2 agreement: {stem}"),
            &ref_set,
            &canon(&rs2_nt, RdfFormat::NTriples),
            logical,
        );
        if n > 0 {
            over_budget.push((format!("3->2 agreement: {stem}"), n));
        }
        compared += 1;

        // Cross-tool (reported, not gated): reference 3->2, sbol-rs 2->3, vs original.
        let (rs3_doc, _) =
            sbol_convert::upgrade_from_sbol2(&ref_text, RdfFormat::RdfXml).expect("upgrade ref2");
        report(
            &format!("ref-down->rs-up vs original: {stem}"),
            &canon(&src, RdfFormat::Turtle),
            &canon_graph(rs3_doc.rdf_graph()),
            logical_roundtrip,
        );
    }

    eprintln!("\ncross-impl-reference: compared {compared} fixture(s)");
    assert!(compared > 0, "no reference fixtures found");
    assert!(
        over_budget.is_empty(),
        "same-direction agreement is not logically equivalent to the reference:\n{}",
        over_budget
            .iter()
            .map(|(label, actual)| format!("  {label}: {actual} divergent triple(s)"))
            .collect::<Vec<_>>()
            .join("\n"),
    );
}
