//! TopLevel provenance, GenericTopLevel, Implementation, Attachment, and
//! Experiment rules (102xx provenance, 103xx, 123xx, 131xx, 132xx, 134xx).

use super::common::{PositiveCase, RuleCase};
use sbol2::validation::Severity::{Error, Warning};

pub fn cases() -> Vec<RuleCase> {
    vec![
        RuleCase {
            name: "wasGeneratedBy refers to a non-Activity object",
            rule: "sbol2-10222",
            severity: Error,
            body: r#"<http://ex/cd> a sbol:ComponentDefinition ;
    sbol:displayId "cd" ;
    sbol:persistentIdentity <http://ex/cd> ;
    sbol:type <http://www.biopax.org/release/biopax-level3.owl#DnaRegion> ;
    prov:wasGeneratedBy <http://ex/not-activity> .
<http://ex/not-activity> a sbol:Collection ;
    sbol:displayId "na" ;
    sbol:persistentIdentity <http://ex/not-activity> .
"#,
        },
        RuleCase {
            name: "circular wasGeneratedBy provenance chain",
            rule: "sbol2-10223",
            severity: Error,
            body: r#"<http://ex/cd> a sbol:ComponentDefinition ;
    sbol:displayId "cd" ;
    sbol:persistentIdentity <http://ex/cd> ;
    sbol:type <http://www.biopax.org/release/biopax-level3.owl#DnaRegion> ;
    prov:wasGeneratedBy <http://ex/act> .
<http://ex/act> a prov:Activity ;
    sbol:displayId "act" ;
    sbol:persistentIdentity <http://ex/act> ;
    prov:qualifiedUsage <http://ex/act/u> .
<http://ex/act/u> a prov:Usage ;
    sbol:displayId "u" ;
    sbol:persistentIdentity <http://ex/act/u> ;
    prov:entity <http://ex/cd> .
"#,
        },
        RuleCase {
            name: "Implementation generated by a design Activity",
            rule: "sbol2-10224",
            severity: Error,
            body: generated_object("sbol:Implementation", "http://sbols.org/v2#design"),
        },
        RuleCase {
            name: "non-Implementation generated by a build Activity",
            rule: "sbol2-10225",
            severity: Error,
            body: generated_object("sbol:ComponentDefinition", "http://sbols.org/v2#build"),
        },
        RuleCase {
            name: "non-ExperimentalData generated by a test Activity",
            rule: "sbol2-10226",
            severity: Error,
            body: generated_object("sbol:ComponentDefinition", "http://sbols.org/v2#test"),
        },
        RuleCase {
            name: "Implementation generated by a learn Activity",
            rule: "sbol2-10227",
            severity: Error,
            body: generated_object("sbol:Implementation", "http://sbols.org/v2#learn"),
        },
        RuleCase {
            name: "derived TopLevel version does not follow its source",
            rule: "sbol2-10302",
            severity: Warning,
            body: r#"<http://ex/a> a sbol:ComponentDefinition ;
    sbol:displayId "cd" ;
    sbol:persistentIdentity <http://ex/shared> ;
    sbol:version "1" ;
    sbol:type <http://www.biopax.org/release/biopax-level3.owl#DnaRegion> ;
    prov:wasDerivedFrom <http://ex/b> .
<http://ex/b> a sbol:ComponentDefinition ;
    sbol:displayId "cd" ;
    sbol:persistentIdentity <http://ex/shared> ;
    sbol:version "2" ;
    sbol:type <http://www.biopax.org/release/biopax-level3.owl#DnaRegion> .
"#,
        },
        RuleCase {
            name: "TopLevel attachment reference does not resolve",
            rule: "sbol2-10307",
            severity: Error,
            body: r#"<http://ex/cd> a sbol:ComponentDefinition ;
    sbol:displayId "cd" ;
    sbol:persistentIdentity <http://ex/cd> ;
    sbol:type <http://www.biopax.org/release/biopax-level3.owl#DnaRegion> ;
    sbol:attachment <http://ex/missing-attachment> .
"#,
        },
        RuleCase {
            name: "Collection member reference does not resolve",
            rule: "sbol2-12103",
            severity: Error,
            body: r#"<http://ex/coll> a sbol:Collection ;
    sbol:displayId "coll" ;
    sbol:persistentIdentity <http://ex/coll> ;
    sbol:member <http://ex/missing-member> .
"#,
        },
        RuleCase {
            name: "GenericTopLevel rdfType lies in the SBOL 2 namespace",
            rule: "sbol2-12303",
            severity: Error,
            body: r#"<http://ex/g> a sbol:GenericTopLevel ;
    sbol:displayId "g" ;
    sbol:persistentIdentity <http://ex/g> ;
    sbol:rdfType <http://sbols.org/v2#Foo> .
"#,
        },
        RuleCase {
            name: "Implementation built refers to neither ComponentDefinition nor ModuleDefinition",
            rule: "sbol2-13103",
            severity: Error,
            body: r#"<http://ex/impl> a sbol:Implementation ;
    sbol:displayId "impl" ;
    sbol:persistentIdentity <http://ex/impl> ;
    sbol:built <http://ex/not-def> .
<http://ex/not-def> a sbol:Collection ;
    sbol:displayId "nd" ;
    sbol:persistentIdentity <http://ex/not-def> .
"#,
        },
        RuleCase {
            name: "Attachment format is not an EDAM term",
            rule: "sbol2-13206",
            severity: Warning,
            body: r#"<http://ex/a> a sbol:Attachment ;
    sbol:displayId "a" ;
    sbol:persistentIdentity <http://ex/a> ;
    sbol:source <http://ex/data.bin> ;
    sbol:format <http://example.org/not-edam> .
"#,
        },
        RuleCase {
            name: "Experiment experimentalData refers to a non-ExperimentalData object",
            rule: "sbol2-13404",
            severity: Error,
            body: r#"<http://ex/e> a sbol:Experiment ;
    sbol:displayId "e" ;
    sbol:persistentIdentity <http://ex/e> ;
    sbol:experimentalData <http://ex/not-ed> .
<http://ex/not-ed> a sbol:Collection ;
    sbol:displayId "ned" ;
    sbol:persistentIdentity <http://ex/not-ed> .
"#,
        },
    ]
}

/// A generated TopLevel of `class` whose generating Activity carries an
/// Association with `role`.
fn generated_object(class: &str, role: &str) -> &'static str {
    match (class, role) {
        ("sbol:Implementation", "http://sbols.org/v2#design") => GEN_IMPL_DESIGN,
        ("sbol:ComponentDefinition", "http://sbols.org/v2#build") => GEN_CD_BUILD,
        ("sbol:ComponentDefinition", "http://sbols.org/v2#test") => GEN_CD_TEST,
        ("sbol:Implementation", "http://sbols.org/v2#learn") => GEN_IMPL_LEARN,
        _ => unreachable!(),
    }
}

macro_rules! generated_body {
    ($class:literal, $role:literal, $types:literal) => {
        concat!(
            r#"<http://ex/obj> a "#,
            $class,
            r#" ;
    sbol:displayId "obj" ;
    sbol:persistentIdentity <http://ex/obj> ;"#,
            $types,
            r#"
    prov:wasGeneratedBy <http://ex/act> .
<http://ex/act> a prov:Activity ;
    sbol:displayId "act" ;
    sbol:persistentIdentity <http://ex/act> ;
    prov:qualifiedAssociation <http://ex/act/assoc> .
<http://ex/act/assoc> a prov:Association ;
    sbol:displayId "assoc" ;
    sbol:persistentIdentity <http://ex/act/assoc> ;
    prov:agent <http://ex/agent> ;
    prov:hadRole <"#,
            $role,
            r#"> .
"#
        )
    };
}

const GEN_IMPL_DESIGN: &str =
    generated_body!("sbol:Implementation", "http://sbols.org/v2#design", "");
const GEN_CD_BUILD: &str = generated_body!(
    "sbol:ComponentDefinition",
    "http://sbols.org/v2#build",
    "\n    sbol:type <http://www.biopax.org/release/biopax-level3.owl#DnaRegion> ;"
);
const GEN_CD_TEST: &str = generated_body!(
    "sbol:ComponentDefinition",
    "http://sbols.org/v2#test",
    "\n    sbol:type <http://www.biopax.org/release/biopax-level3.owl#DnaRegion> ;"
);
const GEN_IMPL_LEARN: &str =
    generated_body!("sbol:Implementation", "http://sbols.org/v2#learn", "");

pub fn positives() -> Vec<PositiveCase> {
    vec![
        PositiveCase {
            name: "wasGeneratedBy resolves to an Activity",
            rule: "sbol2-10222",
            body: r#"<http://ex/cd> a sbol:ComponentDefinition ;
    sbol:displayId "cd" ;
    sbol:persistentIdentity <http://ex/cd> ;
    sbol:type <http://www.biopax.org/release/biopax-level3.owl#DnaRegion> ;
    prov:wasGeneratedBy <http://ex/act> .
<http://ex/act> a prov:Activity ;
    sbol:displayId "act" ;
    sbol:persistentIdentity <http://ex/act> .
"#,
        },
        PositiveCase {
            name: "acyclic wasGeneratedBy provenance chain",
            rule: "sbol2-10223",
            body: r#"<http://ex/cd> a sbol:ComponentDefinition ;
    sbol:displayId "cd" ;
    sbol:persistentIdentity <http://ex/cd> ;
    sbol:type <http://www.biopax.org/release/biopax-level3.owl#DnaRegion> ;
    prov:wasGeneratedBy <http://ex/act> .
<http://ex/act> a prov:Activity ;
    sbol:displayId "act" ;
    sbol:persistentIdentity <http://ex/act> ;
    prov:qualifiedUsage <http://ex/act/u> .
<http://ex/act/u> a prov:Usage ;
    sbol:displayId "u" ;
    sbol:persistentIdentity <http://ex/act/u> ;
    prov:entity <http://ex/other> .
"#,
        },
        PositiveCase {
            name: "non-Implementation TopLevel generated by a design Activity",
            rule: "sbol2-10224",
            body: GEN_CD_DESIGN,
        },
        PositiveCase {
            name: "Implementation generated by a build Activity",
            rule: "sbol2-10225",
            body: GEN_IMPL_BUILD,
        },
        PositiveCase {
            name: "ExperimentalData generated by a test Activity",
            rule: "sbol2-10226",
            body: GEN_ED_TEST,
        },
        PositiveCase {
            name: "non-Implementation generated by a learn Activity",
            rule: "sbol2-10227",
            body: GEN_CD_LEARN,
        },
        PositiveCase {
            name: "derived TopLevel version follows its source",
            rule: "sbol2-10302",
            body: r#"<http://ex/a> a sbol:ComponentDefinition ;
    sbol:displayId "cd" ;
    sbol:persistentIdentity <http://ex/shared> ;
    sbol:version "2" ;
    sbol:type <http://www.biopax.org/release/biopax-level3.owl#DnaRegion> ;
    prov:wasDerivedFrom <http://ex/b> .
<http://ex/b> a sbol:ComponentDefinition ;
    sbol:displayId "cd" ;
    sbol:persistentIdentity <http://ex/shared> ;
    sbol:version "1" ;
    sbol:type <http://www.biopax.org/release/biopax-level3.owl#DnaRegion> .
"#,
        },
        PositiveCase {
            name: "TopLevel attachment reference resolves to an Attachment",
            rule: "sbol2-10307",
            body: r#"<http://ex/cd> a sbol:ComponentDefinition ;
    sbol:displayId "cd" ;
    sbol:persistentIdentity <http://ex/cd> ;
    sbol:type <http://www.biopax.org/release/biopax-level3.owl#DnaRegion> ;
    sbol:attachment <http://ex/att> .
<http://ex/att> a sbol:Attachment ;
    sbol:displayId "att" ;
    sbol:persistentIdentity <http://ex/att> ;
    sbol:source <http://ex/data.bin> .
"#,
        },
        PositiveCase {
            name: "Collection member reference resolves to a TopLevel",
            rule: "sbol2-12103",
            body: r#"<http://ex/coll> a sbol:Collection ;
    sbol:displayId "coll" ;
    sbol:persistentIdentity <http://ex/coll> ;
    sbol:member <http://ex/m> .
<http://ex/m> a sbol:ComponentDefinition ;
    sbol:displayId "m" ;
    sbol:persistentIdentity <http://ex/m> ;
    sbol:type <http://www.biopax.org/release/biopax-level3.owl#DnaRegion> .
"#,
        },
        PositiveCase {
            name: "GenericTopLevel rdfType outside the SBOL 2 namespace",
            rule: "sbol2-12303",
            body: r#"<http://ex/g> a sbol:GenericTopLevel ;
    sbol:displayId "g" ;
    sbol:persistentIdentity <http://ex/g> ;
    sbol:rdfType <http://example.org/Custom> .
"#,
        },
        PositiveCase {
            name: "Implementation built refers to a ComponentDefinition",
            rule: "sbol2-13103",
            body: r#"<http://ex/impl> a sbol:Implementation ;
    sbol:displayId "impl" ;
    sbol:persistentIdentity <http://ex/impl> ;
    sbol:built <http://ex/cd> .
<http://ex/cd> a sbol:ComponentDefinition ;
    sbol:displayId "cd" ;
    sbol:persistentIdentity <http://ex/cd> ;
    sbol:type <http://www.biopax.org/release/biopax-level3.owl#DnaRegion> .
"#,
        },
        PositiveCase {
            name: "Attachment format is an EDAM term",
            rule: "sbol2-13206",
            body: r#"<http://ex/a> a sbol:Attachment ;
    sbol:displayId "a" ;
    sbol:persistentIdentity <http://ex/a> ;
    sbol:source <http://ex/data.bin> ;
    sbol:format <http://identifiers.org/edam:format_2585> .
"#,
        },
        PositiveCase {
            name: "Experiment experimentalData refers to an ExperimentalData object",
            rule: "sbol2-13404",
            body: r#"<http://ex/e> a sbol:Experiment ;
    sbol:displayId "e" ;
    sbol:persistentIdentity <http://ex/e> ;
    sbol:experimentalData <http://ex/ed> .
<http://ex/ed> a sbol:ExperimentalData ;
    sbol:displayId "ed" ;
    sbol:persistentIdentity <http://ex/ed> .
"#,
        },
    ]
}

const GEN_CD_DESIGN: &str = generated_body!(
    "sbol:ComponentDefinition",
    "http://sbols.org/v2#design",
    "\n    sbol:type <http://www.biopax.org/release/biopax-level3.owl#DnaRegion> ;"
);
const GEN_IMPL_BUILD: &str =
    generated_body!("sbol:Implementation", "http://sbols.org/v2#build", "");
const GEN_ED_TEST: &str = generated_body!("sbol:ExperimentalData", "http://sbols.org/v2#test", "");
const GEN_CD_LEARN: &str = generated_body!(
    "sbol:ComponentDefinition",
    "http://sbols.org/v2#learn",
    "\n    sbol:type <http://www.biopax.org/release/biopax-level3.owl#DnaRegion> ;"
);
