//! Hermetic per-rule cases: minimal in-memory SBOL 2 documents that isolate a
//! single rule, with a positive fixture that must not report it and a negative
//! fixture that must. These are fast and require no corpus download; they pin
//! the behavior of each implemented rule family.

use sbol2::validation::{ValidationConfig, ValidationReport};
use sbol2::{Document, RdfFormat};

fn doc(turtle: &str) -> Document {
    Document::read(turtle, RdfFormat::Turtle)
        .unwrap_or_else(|error| panic!("fixture failed to parse: {error}\n{turtle}"))
}

fn reports_rule(report: &ValidationReport, rule: &str) -> bool {
    report.errors().any(|issue| issue.rule == rule)
}

const PREAMBLE: &str = "@prefix sbol: <http://sbols.org/v2#> .\n\
     @prefix prov: <http://www.w3.org/ns/prov#> .\n\
     @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\n";

// 10402: a Sequence requires exactly one elements value.
#[test]
fn sequence_elements_cardinality_10402() {
    let valid = doc(&format!(
        "{PREAMBLE}\
         <http://ex/s1> a sbol:Sequence ;\n\
           sbol:displayId \"s1\" ;\n\
           sbol:persistentIdentity <http://ex/s1> ;\n\
           sbol:elements \"ATCG\" ;\n\
           sbol:encoding <http://sbols.org/v2#IUPACDNA> .\n"
    ));
    assert!(!reports_rule(&valid.validate(), "sbol2-10402"));

    let invalid = doc(&format!(
        "{PREAMBLE}\
         <http://ex/s1> a sbol:Sequence ;\n\
           sbol:displayId \"s1\" ;\n\
           sbol:persistentIdentity <http://ex/s1> ;\n\
           sbol:encoding <http://sbols.org/v2#IUPACDNA> .\n"
    ));
    assert!(reports_rule(&invalid.validate(), "sbol2-10402"));
}

// 10204: displayId must not begin with a digit.
#[test]
fn display_id_syntax_10204() {
    let invalid = doc(&format!(
        "{PREAMBLE}\
         <http://ex/9bad> a sbol:Sequence ;\n\
           sbol:displayId \"9bad\" ;\n\
           sbol:persistentIdentity <http://ex/9bad> ;\n\
           sbol:elements \"A\" ;\n\
           sbol:encoding <http://sbols.org/v2#IUPACDNA> .\n"
    ));
    // A leading-digit displayId is caught regardless of the compliant flag.
    let report = invalid.validate_with_config(&ValidationConfig::default().with_compliant(false));
    assert!(reports_rule(&report, "sbol2-10204"));
}

// 10216: a compliant TopLevel persistentIdentity must end with a delimiter
// followed by its displayId. Gated on the compliant family.
#[test]
fn compliant_persistent_identity_10216() {
    let turtle = format!(
        "{PREAMBLE}\
         <http://ex/s1> a sbol:Sequence ;\n\
           sbol:displayId \"s1\" ;\n\
           sbol:persistentIdentity <http://ex/mismatch> ;\n\
           sbol:elements \"A\" ;\n\
           sbol:encoding <http://sbols.org/v2#IUPACDNA> .\n"
    );
    let document = doc(&turtle);
    // Off when the compliant family is disabled.
    let off = document.validate_with_config(&ValidationConfig::default().with_compliant(false));
    assert!(!reports_rule(&off, "sbol2-10216"));
    // On under the default (compliant) config.
    assert!(reports_rule(&document.validate(), "sbol2-10216"));
}

// 10604: a FunctionalComponent definition must resolve in a complete document.
// Gated on the completeness family.
#[test]
fn completeness_definition_10604() {
    let turtle = format!(
        "{PREAMBLE}\
         <http://ex/md/1> a sbol:ModuleDefinition ;\n\
           sbol:displayId \"md\" ;\n\
           sbol:persistentIdentity <http://ex/md> ;\n\
           sbol:functionalComponent <http://ex/md/fc/1> .\n\
         <http://ex/md/fc/1> a sbol:FunctionalComponent ;\n\
           sbol:displayId \"fc\" ;\n\
           sbol:persistentIdentity <http://ex/md/fc> ;\n\
           sbol:access <http://sbols.org/v2#public> ;\n\
           sbol:direction <http://sbols.org/v2#inout> ;\n\
           sbol:definition <http://ex/absent_cd> .\n"
    );
    let document = doc(&turtle);
    let off = document.validate_with_config(&ValidationConfig::default().with_complete(false));
    assert!(!reports_rule(&off, "sbol2-10604"));
    assert!(reports_rule(&document.validate(), "sbol2-10604"));
}

// 10225: an object generated by a build Activity should be an Implementation.
// Gated on the best-practice family.
#[test]
fn provenance_build_role_10225() {
    let turtle = format!(
        "{PREAMBLE}\
         <http://ex/cd/1> a sbol:ComponentDefinition ;\n\
           sbol:displayId \"cd\" ;\n\
           sbol:persistentIdentity <http://ex/cd> ;\n\
           sbol:type <http://www.biopax.org/release/biopax-level3.owl#DnaRegion> ;\n\
           prov:wasGeneratedBy <http://ex/act/1> .\n\
         <http://ex/act/1> a prov:Activity ;\n\
           sbol:displayId \"act\" ;\n\
           sbol:persistentIdentity <http://ex/act> ;\n\
           prov:qualifiedAssociation <http://ex/act/assoc/1> .\n\
         <http://ex/act/assoc/1> a prov:Association ;\n\
           sbol:displayId \"assoc\" ;\n\
           sbol:persistentIdentity <http://ex/act/assoc> ;\n\
           prov:agent <http://ex/agent> ;\n\
           prov:hadRole <http://sbols.org/v2#build> .\n"
    );
    let document = doc(&turtle);
    // Off when best-practice checking is disabled (the default).
    assert!(!reports_rule(&document.validate(), "sbol2-10225"));
    // On when best-practice checking is enabled.
    let on = document.validate_with_config(&ValidationConfig::default().with_best_practice(true));
    assert!(reports_rule(&on, "sbol2-10225"));
}
