//! Per-rule regression coverage gate over the SBOL 2 rule catalog. Mirrors
//! `crates/sbol3/tests/validation_rules.rs`: every machine-checkable rule must
//! carry a firing negative fixture (a document that reports the rule at its
//! catalog severity) and a non-firing positive fixture (a valid instance that
//! does not). The gate is real: a rule without either fixture fails the suite.

use std::collections::{BTreeMap, BTreeSet};

mod rule_cases;
use rule_cases::{
    all_on, all_positive_cases, all_rule_cases, read_case, read_positive_case, reports_any,
    reports_at,
};

use sbol2::validation::{RuleStatus, validation_rule_statuses};

/// Every machine-checkable rule (status Error, Warning, or Configurable) must
/// have a negative regression case; MachineUncheckable rules do not.
fn machine_checkable_rules() -> Vec<&'static str> {
    validation_rule_statuses()
        .iter()
        .filter(|status| {
            matches!(
                status.status,
                RuleStatus::Error | RuleStatus::Warning | RuleStatus::Configurable
            )
        })
        .map(|status| status.rule)
        .collect()
}

#[test]
fn machine_checkable_rules_have_negative_cases() {
    let covered: BTreeSet<&str> = all_rule_cases().iter().map(|case| case.rule).collect();
    let mut missing: Vec<&str> = Vec::new();
    for rule in machine_checkable_rules() {
        if !covered.contains(rule) {
            missing.push(rule);
        }
    }
    assert!(
        missing.is_empty(),
        "machine-checkable rules without a negative case ({}): {:?}",
        missing.len(),
        missing
    );

    // Every negative case names a catalog rule.
    let catalog: BTreeSet<&str> = validation_rule_statuses()
        .iter()
        .map(|status| status.rule)
        .collect();
    for case in all_rule_cases() {
        assert!(
            catalog.contains(case.rule),
            "negative case `{}` names unknown rule {}",
            case.name,
            case.rule
        );
    }
}

#[test]
fn machine_checkable_rules_have_positive_cases() {
    let covered: BTreeSet<&str> = all_positive_cases().iter().map(|case| case.rule).collect();
    let mut missing: Vec<&str> = Vec::new();
    for rule in machine_checkable_rules() {
        if !covered.contains(rule) {
            missing.push(rule);
        }
    }
    assert!(
        missing.is_empty(),
        "machine-checkable rules without a positive case ({}): {:?}",
        missing.len(),
        missing
    );
}

#[test]
fn negative_cases_report_expected_rule_ids() {
    let config = all_on();
    let mut failures: Vec<String> = Vec::new();
    for case in all_rule_cases() {
        let document = read_case(case);
        let report = document.validate_with_config(&config);
        if !reports_at(&report, case.rule, case.severity) {
            failures.push(format!(
                "{} ({}) did not report {} as {:?}",
                case.name, case.rule, case.rule, case.severity
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "negative cases that did not fire ({}):\n  {}",
        failures.len(),
        failures.join("\n  ")
    );
}

#[test]
fn positive_cases_do_not_report_their_rule() {
    let config = all_on();
    let mut failures: Vec<String> = Vec::new();
    for case in all_positive_cases() {
        let document = read_positive_case(case);
        let report = document.validate_with_config(&config);
        if reports_any(&report, case.rule) {
            failures.push(format!(
                "{} ({}) unexpectedly reported",
                case.name, case.rule
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "positive cases that wrongly fired ({}):\n  {}",
        failures.len(),
        failures.join("\n  ")
    );
}

/// Renders the per-rule negative + positive coverage matrix committed at
/// `docs/sbol2-negative-coverage.md`.
fn render_coverage_matrix() -> String {
    use std::fmt::Write as _;

    let mut negatives: BTreeMap<&str, usize> = BTreeMap::new();
    for case in all_rule_cases() {
        *negatives.entry(case.rule).or_default() += 1;
    }
    let mut positives: BTreeMap<&str, usize> = BTreeMap::new();
    for case in all_positive_cases() {
        *positives.entry(case.rule).or_default() += 1;
    }

    let machine_checkable: Vec<_> = validation_rule_statuses()
        .iter()
        .filter(|status| {
            matches!(
                status.status,
                RuleStatus::Error | RuleStatus::Warning | RuleStatus::Configurable
            )
        })
        .collect();

    let mut out = String::new();
    out.push_str("# SBOL 2.3.0 negative + positive coverage matrix\n\n");
    out.push_str(
        "Generated by `SBOL2_UPDATE_NEGATIVE_COVERAGE=1 cargo test -p sbol2 --test \
         validation_rules negative_coverage_matrix_matches_committed_file`. CI runs the same \
         test without the variable as a freshness gate.\n\n",
    );
    writeln!(
        out,
        "Every one of the {} machine-checkable rules has at least one negative fixture (a \
         violating document asserted to report the rule at its catalog severity) and at least \
         one positive fixture (a valid instance asserted not to report it), all evaluated under \
         `ValidationConfig::all_on()`.\n",
        machine_checkable.len()
    )
    .unwrap();

    out.push_str("| Rule | Section | Status | Normative | Negatives | Positives |\n");
    out.push_str("|------|---------|--------|-----------|-----------|-----------|\n");
    for status in &machine_checkable {
        let neg = negatives.get(status.rule).copied().unwrap_or(0);
        let pos = positives.get(status.rule).copied().unwrap_or(0);
        writeln!(
            out,
            "| {} | {} | {:?} | {:?} | {} | {} |",
            status.rule, status.spec_section, status.status, status.normative_severity, neg, pos
        )
        .unwrap();
    }
    let total_neg: usize = negatives.values().sum();
    let total_pos: usize = positives.values().sum();
    writeln!(
        out,
        "\nTotals: {} machine-checkable rules, {} negative cases, {} positive cases.",
        machine_checkable.len(),
        total_neg,
        total_pos
    )
    .unwrap();
    out
}

#[test]
fn negative_coverage_matrix_matches_committed_file() {
    let rendered = render_coverage_matrix();
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(std::path::Path::parent)
        .expect("workspace root")
        .join("docs")
        .join("sbol2-negative-coverage.md");

    if std::env::var_os("SBOL2_UPDATE_NEGATIVE_COVERAGE").is_some() {
        std::fs::write(&path, &rendered).expect("write sbol2-negative-coverage.md");
        return;
    }
    let committed = std::fs::read_to_string(&path).unwrap_or_default();
    assert_eq!(
        committed, rendered,
        "docs/sbol2-negative-coverage.md is stale. Run `SBOL2_UPDATE_NEGATIVE_COVERAGE=1 cargo \
         test -p sbol2 --test validation_rules negative_coverage_matrix_matches_committed_file`."
    );
}
